CLASS zcl_lab_09_account_t100598 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  METHODS: set_iban IMPORTING IBAN TYPE STRING,
           get_iban EXPORTING IBAN TYPE STRING.
  PROTECTED SECTION.
  PRIVATE SECTION.
  DATA IBAN TYPE STRING.
ENDCLASS.



CLASS zcl_lab_09_account_t100598 IMPLEMENTATION.
  METHOD get_iban.
   iban = me->iban.
  ENDMETHOD.

  METHOD set_iban.
   me->iban = iban.
  ENDMETHOD.

ENDCLASS.
